"""
Authentication and Security Utilities
-------------------------------------

AI Crime Investigator authentication module.

This module handles:

    - Password hashing
    - Password verification
    - Session management
    - Pending 2FA challenges
    - TOTP secret generation
    - TOTP code generation
    - TOTP verification
    - Authenticator provisioning URI

No external authentication framework is required.
"""

import base64
import hashlib
import hmac
import secrets
import struct
import time
from urllib.parse import quote


# ============================================================
# PASSWORD HASHING CONFIGURATION
# ============================================================

# PBKDF2 iteration count.
#
# Stored hashes generated by this application use this value.
# Keeping it in one place makes future upgrades easier.

PBKDF2_ITERATIONS = 120000

PASSWORD_SALT_BYTES = 16

PASSWORD_HASH_ALGORITHM = "sha256"


# ============================================================
# PASSWORD HASHING
# ============================================================

def hash_password(password: str):
    """
    Create a secure password hash using
    PBKDF2-HMAC-SHA256.

    Stored format:

        base64(salt):base64(hash)

    Example:

        abc123...:xyz789...
    """

    if password is None:
        raise ValueError(
            "Password cannot be None."
        )

    if not isinstance(password, str):
        password = str(password)

    if password == "":
        raise ValueError(
            "Password cannot be empty."
        )

    # Generate a cryptographically secure random salt.
    salt = secrets.token_bytes(
        PASSWORD_SALT_BYTES
    )

    # Derive password hash.
    password_hash = hashlib.pbkdf2_hmac(
        PASSWORD_HASH_ALGORITHM,
        password.encode("utf-8"),
        salt,
        PBKDF2_ITERATIONS
    )

    # Encode salt and hash for database storage.
    salt_b64 = base64.b64encode(
        salt
    ).decode("ascii")

    hash_b64 = base64.b64encode(
        password_hash
    ).decode("ascii")

    return f"{salt_b64}:{hash_b64}"


# ============================================================
# PASSWORD VERIFICATION
# ============================================================

def verify_password(
    password: str,
    stored_password: str
):
    """
    Verify a plain-text password against a stored
    PBKDF2 password hash.

    Returns:

        True  -> password is correct
        False -> password is incorrect/invalid
    """

    try:

        if password is None:
            return False

        if stored_password is None:
            return False

        if not isinstance(password, str):
            password = str(password)

        if not isinstance(stored_password, str):
            stored_password = str(
                stored_password
            )

        # ----------------------------------------------------
        # Split stored value.
        # ----------------------------------------------------

        parts = stored_password.split(":")

        if len(parts) != 2:
            return False

        salt_b64, hash_b64 = parts

        if not salt_b64 or not hash_b64:
            return False

        # ----------------------------------------------------
        # Decode salt and expected hash.
        # ----------------------------------------------------

        salt = base64.b64decode(
            salt_b64,
            validate=True
        )

        expected_hash = base64.b64decode(
            hash_b64,
            validate=True
        )

        if not salt or not expected_hash:
            return False

        # ----------------------------------------------------
        # Recalculate password hash.
        # ----------------------------------------------------

        actual_hash = hashlib.pbkdf2_hmac(
            PASSWORD_HASH_ALGORITHM,
            password.encode("utf-8"),
            salt,
            PBKDF2_ITERATIONS
        )

        # ----------------------------------------------------
        # Constant-time comparison.
        # ----------------------------------------------------

        return hmac.compare_digest(
            actual_hash,
            expected_hash
        )

    except Exception:

        return False


# ============================================================
# SESSION MANAGEMENT
# ============================================================

# Simple in-memory session storage.
#
# Format:
#
#     {
#         "random-session-token": "username"
#     }
#
# NOTE:
# This is suitable for a local/demo project.
# Sessions disappear when the FastAPI process restarts.

ACTIVE_SESSIONS = {}


# ============================================================
# CREATE SESSION
# ============================================================

def create_session(username):
    """
    Create a new authenticated session.

    Returns:
        session token
    """

    if username is None:
        raise ValueError(
            "Username is required."
        )

    username = str(
        username
    ).strip()

    if not username:
        raise ValueError(
            "Username cannot be empty."
        )

    # Generate a cryptographically secure token.
    token = secrets.token_urlsafe(32)

    ACTIVE_SESSIONS[token] = username

    return token


# ============================================================
# GET SESSION USER
# ============================================================

def get_session_user(token):
    """
    Get the username associated with a session token.

    Returns:
        username -> valid session
        None     -> invalid/expired session
    """

    if not token:
        return None

    return ACTIVE_SESSIONS.get(
        str(token).strip()
    )


# ============================================================
# REMOVE SESSION
# ============================================================

def remove_session(token):
    """
    Remove an active session.

    Returns:
        True  -> session existed and was removed
        False -> session did not exist
    """

    if not token:
        return False

    token = str(token).strip()

    if token in ACTIVE_SESSIONS:

        del ACTIVE_SESSIONS[token]

        return True

    return False


# ============================================================
# REMOVE ALL USER SESSIONS
# ============================================================

def remove_user_sessions(username):
    """
    Remove all active sessions belonging to a username.

    Useful after password changes or security events.
    """

    if not username:
        return 0

    username = str(
        username
    ).strip()

    tokens_to_remove = [
        token
        for token, session_username
        in ACTIVE_SESSIONS.items()
        if session_username == username
    ]

    for token in tokens_to_remove:

        del ACTIVE_SESSIONS[token]

    return len(
        tokens_to_remove
    )


# ============================================================
# TWO-FACTOR AUTHENTICATION
# ============================================================

# Temporary storage for users who have passed
# password authentication but still need 2FA.
#
# Format:
#
#     {
#         "temporary-token": "username"
#     }

PENDING_2FA = {}


# ============================================================
# CREATE 2FA CHALLENGE
# ============================================================

def create_2fa_challenge(username):
    """
    Create a temporary challenge after successful
    password authentication.

    The user must complete 2FA before receiving
    a normal authenticated session.
    """

    if username is None:
        raise ValueError(
            "Username is required."
        )

    username = str(
        username
    ).strip()

    if not username:
        raise ValueError(
            "Username cannot be empty."
        )

    token = secrets.token_urlsafe(32)

    PENDING_2FA[token] = username

    return token


# ============================================================
# GET 2FA CHALLENGE
# ============================================================

def get_2fa_challenge(token):
    """
    Get the username associated with a pending
    2FA challenge.

    Returns:
        username -> valid challenge
        None     -> invalid challenge
    """

    if not token:
        return None

    return PENDING_2FA.get(
        str(token).strip()
    )


# ============================================================
# CONSUME 2FA CHALLENGE
# ============================================================

def consume_2fa_challenge(token):
    """
    Consume a completed 2FA challenge.

    Once consumed, the same challenge cannot be reused.

    Returns:
        username -> challenge existed
        None     -> invalid/already consumed
    """

    if not token:
        return None

    token = str(
        token
    ).strip()

    return PENDING_2FA.pop(
        token,
        None
    )


# ============================================================
# REMOVE USER'S PENDING 2FA CHALLENGES
# ============================================================

def remove_user_2fa_challenges(username):
    """
    Remove all pending 2FA challenges belonging
    to a username.
    """

    if not username:
        return 0

    username = str(
        username
    ).strip()

    tokens_to_remove = [
        token
        for token, challenge_username
        in PENDING_2FA.items()
        if challenge_username == username
    ]

    for token in tokens_to_remove:

        del PENDING_2FA[token]

    return len(
        tokens_to_remove
    )


# ============================================================
# TOTP CONFIGURATION
# ============================================================

TOTP_INTERVAL = 30

TOTP_DIGITS = 6

TOTP_SECRET_BYTES = 20

TOTP_HASH_ALGORITHM = hashlib.sha1


# ============================================================
# GENERATE TOTP SECRET
# ============================================================

def generate_totp_secret():
    """
    Generate a Base32 TOTP secret.

    Compatible with authenticator applications such as:

        - Google Authenticator
        - Microsoft Authenticator
        - Authy
        - Other standard TOTP applications

    Returns:
        Base32 encoded secret without '=' padding.
    """

    secret = base64.b32encode(
        secrets.token_bytes(
            TOTP_SECRET_BYTES
        )
    ).decode(
        "ascii"
    ).rstrip("=")

    return secret


# ============================================================
# NORMALIZE TOTP SECRET
# ============================================================

def _decode_totp_secret(secret):
    """
    Decode a Base32 TOTP secret.

    Internal helper.
    """

    if secret is None:
        raise ValueError(
            "TOTP secret is required."
        )

    secret = str(
        secret
    ).strip().replace(
        " ",
        ""
    ).upper()

    if not secret:
        raise ValueError(
            "TOTP secret cannot be empty."
        )

    # Restore Base32 padding.
    padding = "=" * (
        (8 - len(secret) % 8) % 8
    )

    return base64.b32decode(
        secret + padding,
        casefold=True
    )


# ============================================================
# GENERATE TOTP CODE
# ============================================================

def totp_code(
    secret,
    for_time=None
):
    """
    Generate a 6-digit TOTP code.

    A new code is generated every 30 seconds.

    Args:
        secret:
            Base32 TOTP secret.

        for_time:
            Optional Unix timestamp.
            Current time is used if omitted.

    Returns:
        Six-digit string.

    Example:

        "482193"
    """

    key = _decode_totp_secret(
        secret
    )

    # --------------------------------------------------------
    # Time
    # --------------------------------------------------------

    if for_time is None:

        for_time = int(
            time.time()
        )

    else:

        for_time = int(
            for_time
        )

    # --------------------------------------------------------
    # Calculate time counter.
    # --------------------------------------------------------

    counter = int(
        for_time // TOTP_INTERVAL
    )

    # --------------------------------------------------------
    # Convert counter into 8-byte big-endian format.
    # --------------------------------------------------------

    counter_bytes = struct.pack(
        ">Q",
        counter
    )

    # --------------------------------------------------------
    # HMAC-SHA1.
    # --------------------------------------------------------

    digest = hmac.new(
        key,
        counter_bytes,
        TOTP_HASH_ALGORITHM
    ).digest()

    # --------------------------------------------------------
    # Dynamic truncation.
    # --------------------------------------------------------

    offset = (
        digest[-1] & 0x0F
    )

    binary_code = struct.unpack(
        ">I",
        digest[
            offset:offset + 4
        ]
    )[0] & 0x7FFFFFFF

    # --------------------------------------------------------
    # Convert to six digits.
    # --------------------------------------------------------

    code = (
        binary_code
        % (10 ** TOTP_DIGITS)
    )

    return f"{code:0{TOTP_DIGITS}d}"


# ============================================================
# VERIFY TOTP CODE
# ============================================================

def verify_totp(
    secret,
    code,
    window=1
):
    """
    Verify a TOTP authenticator code.

    By default:

        window=1

    checks:

        previous 30 seconds
        current 30 seconds
        next 30 seconds

    This allows a small clock difference between
    the server and authenticator device.

    Returns:
        True  -> valid
        False -> invalid
    """

    try:

        if not secret:
            return False

        if code is None:
            return False

        code = str(
            code
        ).strip()

        # TOTP must contain exactly six digits.
        if len(code) != TOTP_DIGITS:
            return False

        if not code.isdigit():
            return False

        window = int(
            window
        )

        # Prevent unreasonable verification windows.
        if window < 0:
            window = 0

        if window > 5:
            window = 5

        now = int(
            time.time()
        )

        # ----------------------------------------------------
        # Check previous/current/next time windows.
        # ----------------------------------------------------

        for step in range(
            -window,
            window + 1
        ):

            generated_code = totp_code(
                secret,
                now + (
                    step * TOTP_INTERVAL
                )
            )

            if hmac.compare_digest(
                generated_code,
                code
            ):
                return True

        return False

    except Exception:

        return False


# ============================================================
# TOTP AUTHENTICATOR SETUP URI
# ============================================================

def totp_provisioning_uri(
    secret,
    email,
    issuer="AI Crime Investigator"
):
    """
    Generate an RFC-compatible otpauth:// URI.

    Authenticator applications can use this URI to
    configure the TOTP account.

    Example format:

        otpauth://totp/Issuer:email
        ?secret=SECRET
        &issuer=Issuer
        &algorithm=SHA1
        &digits=6
        &period=30
    """

    if not secret:
        raise ValueError(
            "TOTP secret is required."
        )

    if not email:
        raise ValueError(
            "Email is required."
        )

    if not issuer:
        issuer = "AI Crime Investigator"

    secret = str(
        secret
    ).strip()

    email = str(
        email
    ).strip()

    issuer = str(
        issuer
    ).strip()

    # --------------------------------------------------------
    # Encode label.
    # --------------------------------------------------------

    label = f"{issuer}:{email}"

    encoded_label = quote(
        label,
        safe=""
    )

    encoded_issuer = quote(
        issuer,
        safe=""
    )

    # --------------------------------------------------------
    # Build otpauth URI.
    # --------------------------------------------------------

    return (
        "otpauth://totp/"
        f"{encoded_label}"
        f"?secret={quote(secret, safe='')}"
        f"&issuer={encoded_issuer}"
        f"&algorithm=SHA1"
        f"&digits={TOTP_DIGITS}"
        f"&period={TOTP_INTERVAL}"
    )